### PR TITLE
rework and integrate bulma adder

### PR DESCRIPTION
**Pull request by manuel3108**
I tried to make the bulma adder a "real" adder.
I copied a lot of stuff from the scss adder.

The only problem I see at the moment is that we are removing the demos we previously had. I currently don't know if we have them anywhere else, so that I could just copy some stuff.

But in my opinion we could even leave them out, as the readme already explains a lot.

What are your opinions?

### CODE REVIEW

**Comment by babichjacob** [comment]
> The only problem I see at the moment is that we are removing the demos we previously had. I currently don't know if we have them anywhere else, so that I could just copy some stuff.

`svelte-add` currently does not have an example code / demos feature yet, so when I program it I will reach back in the commit history to find the example files to re-add them, so it's okay that they're being removed now.

**Comment by babichjacob** [comment]
I think the `imports` detection is too strict. Since people are allowed to remove what they don't want from Bulma, we should only detect that there's at least one Bulma import. In which case `appScss.includes("bulma")` is good enough!

I will clean up any things across the recent PRs that I might want to tweak.

**Comment by babichjacob** [comment]
> You can modify your design in src/app.scss and in example add $body-background-color: blue; above the import statements. 

We can do this in `src/variables.scss` (that the [SCSS adder](https://github.com/svelte-add/scss) creates) and it still work, right?
> You can write SCSS syntax in the src/variables.scss file.
> Variables and mixins written here are automatically available to all other SCSS files and style lang="scss" blocks in Svelte files without needing to import this file.

**Comment by manuel3108** [comment]
TBH, didn't try that out.
Sure no problem.

As for the detection:
From my understanding the detect stuff was only run to see if bulma was installed immeaditly after the installation. But if its run on any other ocasion, you are definitly right

**Comment by babichjacob** [comment]
My changes are in https://github.com/svelte-add/bulma/commit/f95f24ceea11edf56247d6814852c22937da84c0 and have been published to npm.

Thank you very much!

**Comment by manuel3108** [comment]
Works great, thanks for the fast publish 👍 (Same goes for Bootstrap btw)

**Pull request merged**
